<?php

/**
 * @file
 * Enables the PrEP decision aid
 */

/**
 * Implements hook_preprocess_page()
 */
function prep_decision_aid_preprocess_page(&$variables) {
  $module_path = drupal_get_path('module', 'prep_decision_aid');
  if (current_path() == 'prep_decision_aid') {
    //drupal_add_js($module_path . '/js/react.min.js', array('scope' => 'footer') );
    //drupal_add_js($module_path . '/js/react-dom.min.js', array('scope' => 'footer') );
    drupal_add_js($module_path . '/js/up_app.js', array('scope' => 'footer') );
    drupal_add_css($module_path . '/css/index.css');
    drupal_add_css($module_path . '/css/up_styles.css');
  }
}


/**
 * Implements hook_menu().
 */
function prep_decision_aid_menu() {

  $items['prep_decision_aid'] = array(
    //'title' => 'A decision tool for men and their health providers',
    //'title callback' => 'prep_title',
    //'title arguments' => array('New title'),
    'description' => 'A decision tool for men and their health providers.',
    'page callback' => 'take_the_4_steps',
    'access arguments' => array('access content'),
  );

  return $items;
}

/*
function prep_title ($title) {
  //return '<div class="prep-title">' . $title . '</div>';
  $output = array(
    '#type' => 'markup',
    '#markup' => $title,
    '#prefix' => '<div class="test">',
    '#suffix' => '</div>'
  );
  return render($output);
  
}
 */

/**
 * Load decision aid page
 */
function take_the_4_steps() {
  return '<div id="up-app"></div>';
  //return theme('prep_decision_aid_theme');
}

/**
 * Implements hook_theme()
 */
/*
function prep_decision_aid_theme() {
  return array(
    'prep_decision_aid_template' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'template' => 'templates/prep_decision_aid',
    ),
  );
}

function template_preprocess_prep_decision_aid_template(&$variables) {
  $node = $variables['node'];
  $variables['title'] = array(
    '#type' => 'markup',
    '#title' => $node-> title
  );
}
 */

